/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_trilead_ssh2_signature_Ed25519Verify */

#ifndef _Included_com_trilead_ssh2_signature_Ed25519Verify
#define _Included_com_trilead_ssh2_signature_Ed25519Verify
#ifdef __cplusplus
extern "C" {
#endif
#undef com_trilead_ssh2_signature_Ed25519Verify_ED25519_PK_SIZE_BYTES
#define com_trilead_ssh2_signature_Ed25519Verify_ED25519_PK_SIZE_BYTES 32L
#undef com_trilead_ssh2_signature_Ed25519Verify_ED25519_SK_SIZE_BYTES
#define com_trilead_ssh2_signature_Ed25519Verify_ED25519_SK_SIZE_BYTES 64L
#undef com_trilead_ssh2_signature_Ed25519Verify_ED25519_SIG_SIZE_BYTES
#define com_trilead_ssh2_signature_Ed25519Verify_ED25519_SIG_SIZE_BYTES 64L
/*
 * Class:     com_trilead_ssh2_signature_Ed25519Verify
 * Method:    crypto_sign_ed25519
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_trilead_ssh2_signature_Ed25519Verify_crypto_1sign_1ed25519
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     com_trilead_ssh2_signature_Ed25519Verify
 * Method:    crypto_sign_ed25519_open
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_trilead_ssh2_signature_Ed25519Verify_crypto_1sign_1ed25519_1open
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
